-- =============================================================================
-- Industrial Telemetry Platform — TimescaleDB Schema
-- =============================================================================
-- Run against a PostgreSQL database with the TimescaleDB extension installed.
--
-- Table responsibilities:
--   devices       → static metadata (changes rarely)
--   telemetry     → append-only time-series readings (hypertable)
--   device_health → latest computed state per device (updated frequently)
--   alerts        → significant events over time (written by analytics worker)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS timescaledb;

-- -----------------------------------------------------------------------------
-- TABLE 1: devices
-- -----------------------------------------------------------------------------
-- Stores metadata for every monitored device.
-- Intentionally excludes live metrics and health_score — see device_health.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS devices (
  id          UUID        PRIMARY KEY,
  name        TEXT        NOT NULL UNIQUE,
  type        TEXT        NOT NULL,
  location    TEXT,
  status      TEXT        NOT NULL DEFAULT 'healthy'
    CHECK (status IN ('healthy', 'warning', 'critical', 'offline')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE devices IS 'Static metadata for monitored industrial devices.';
COMMENT ON COLUMN devices.type IS 'Equipment category, e.g. Motor, Pump, Cooling Unit.';
COMMENT ON COLUMN devices.status IS 'Operational status snapshot; latest computed state lives in device_health.';

CREATE INDEX IF NOT EXISTS idx_devices_status
  ON devices (status);

CREATE INDEX IF NOT EXISTS idx_devices_type
  ON devices (type);

-- -----------------------------------------------------------------------------
-- TABLE 2: telemetry
-- -----------------------------------------------------------------------------
-- Stores every incoming sensor reading. Converted to a TimescaleDB hypertable
-- partitioned on recorded_at for efficient time-range queries and retention.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS telemetry (
  id            BIGSERIAL         NOT NULL,
  device_id     UUID              NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
  temperature   DOUBLE PRECISION,
  pressure      DOUBLE PRECISION,
  power         DOUBLE PRECISION,
  vibration     DOUBLE PRECISION,
  recorded_at   TIMESTAMPTZ       NOT NULL,
  PRIMARY KEY (id, recorded_at)
);

COMMENT ON TABLE telemetry IS 'Append-only time-series sensor readings per device.';
COMMENT ON COLUMN telemetry.pressure IS 'Nullable for device types without pressure sensors (e.g. motors).';

COMMENT ON COLUMN telemetry.id IS 'Surrogate key; composite PK includes recorded_at for TimescaleDB partitioning.';

SELECT create_hypertable(
  'telemetry',
  'recorded_at',
  if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS idx_telemetry_device_recorded_at
  ON telemetry (device_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_recorded_at
  ON telemetry (recorded_at DESC);

-- -----------------------------------------------------------------------------
-- TABLE 3: alerts
-- -----------------------------------------------------------------------------
-- Stores alerts generated by the analytics worker and shown in the dashboard.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS alerts (
  id           BIGSERIAL    PRIMARY KEY,
  device_id    UUID         NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
  severity     TEXT         NOT NULL
    CHECK (severity IN ('info', 'warning', 'critical')),
  type         TEXT         NOT NULL,
  message      TEXT         NOT NULL,
  status       TEXT         NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'acknowledged', 'resolved')),
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  resolved_at  TIMESTAMPTZ
);

COMMENT ON TABLE alerts IS 'Historical alerts raised by the analytics pipeline.';
COMMENT ON COLUMN alerts.type IS 'Machine-readable alert category, e.g. overheating, pressure_loss, bearing_failure.';

CREATE INDEX IF NOT EXISTS idx_alerts_device_created_at
  ON alerts (device_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_status_created_at
  ON alerts (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_severity_created_at
  ON alerts (severity, created_at DESC);

-- -----------------------------------------------------------------------------
-- TABLE 4: device_health
-- -----------------------------------------------------------------------------
-- Stores the latest calculated health for every device.
-- Updated by the analytics worker; avoids recomputing from raw telemetry on reads.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS device_health (
  device_id         UUID             PRIMARY KEY REFERENCES devices (id) ON DELETE CASCADE,
  health_score      INTEGER          NOT NULL DEFAULT 100
    CHECK (health_score >= 0 AND health_score <= 100),
  status            TEXT             NOT NULL DEFAULT 'healthy'
    CHECK (status IN ('healthy', 'warning', 'critical', 'offline')),
  last_temperature  DOUBLE PRECISION,
  last_pressure     DOUBLE PRECISION,
  last_power        DOUBLE PRECISION,
  last_vibration    DOUBLE PRECISION,
  last_seen         TIMESTAMPTZ,
  updated_at        TIMESTAMPTZ        NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE device_health IS 'Latest computed health and most recent sensor snapshot per device.';
COMMENT ON COLUMN device_health.last_seen IS 'Timestamp of the most recent telemetry reading received.';

CREATE INDEX IF NOT EXISTS idx_device_health_status
  ON device_health (status);

CREATE INDEX IF NOT EXISTS idx_device_health_last_seen
  ON device_health (last_seen DESC);
